(defadvice term-line-mode (after term-line-mode-fixes ())
  (set (make-local-variable 'cua-mode) t)
  (set (make-local-variable 'transient-mark-mode) t))
(defadvice ansi-term (after advice-term-line-mode activate)
  (term-line-mode))
(ad-activate 'term-line-mode)
(provide 'init-term)
