(require-package 'key-chord)
(key-chord-mode 1)
(require-package 'ace-jump-mode)
(require-package 'helm-projectile)
(setq projectile-globally-ignored-files (append projectile-globally-ignored-files
                                                '("GTAGS" "GPATH" "GSYMS" "GRTAGS" "makefile" "*\\.pyc")))
(require 'helm-projectile)
(key-chord-define-global "jj" 'ace-jump-word-mode)
(key-chord-define-global "jl" 'ace-jump-line-mode)
(key-chord-define-global "jk" 'ace-jump-char-mode)
(key-chord-define-global ",," 'ido-switch-buffer)
(key-chord-define-global "uu" 'undo-tree-visualize)
(key-chord-define-global "xx" 'smex)
;(key-chord-define-global "yy" 'browse-kill-ring)
(key-chord-define-global ",." 'helm-projectile-find-file)
(require-package 'hydra)
(key-chord-define-global "yy"
                         (defhydra handy(nil)
                           "easy"
                           ("f" find-file "file")
                           ("3" (progn (split-window-right) (windmove-right)))
                           ("2" (progn (split-window-below) (windmove-down)))
                           ("o" switch-window)
                           ("0" delete-window)
                           ("b" helm-buffers-list)
                           ("j" join-line)
                           ("J" (join-line 1))
                           ("+" text-scale-increase)
                           ("-" text-scale-decrease)
                           ("k" kill-sexp)
                           ("a" my/org-check-agenda)
                           ("." repeat)
                           ("n" next-line)
                           ("p" previous-line)
                           ("v" scroll-up) ("V" scroll-down) ("x" smex)
                           ("q" nil)))

(key-chord-mode +1)
(provide 'init-keychord)
