(require-package 'key-chord)
(key-chord-mode 1)
(require-package 'ace-jump-mode)
(require-package 'helm-projectile)
(setq projectile-globally-ignored-files (append projectile-globally-ignored-files
                                                '("GTAGS" "GPATH" "GSYMS" "GRTAGS" "makefile" "*\\.pyc")))
(require 'helm-projectile)
(key-chord-define-global "jj" 'ace-jump-word-mode)
(key-chord-define-global "jl" 'ace-jump-line-mode)
(key-chord-define-global "jk" 'ace-jump-char-mode)
(key-chord-define-global ",," 'ido-switch-buffer)
(key-chord-define-global "uu" 'undo-tree-visualize)
(key-chord-define-global "xx" 'smex)
(key-chord-define-global "yy" 'browse-kill-ring)
(key-chord-define-global ",." 'helm-projectile-find-file)
(require-package 'hydra)
(key-chord-define-global "yy"
                         (defhydra my/window-movement ()
                           ("<left>" windmove-left)
                           ("<right>" windmove-right)
                           ("<down>" windmove-down)
                           ("<up>" windmove-up)
                           ("y" other-window "other")
                           ("h" switch-window "switch-window")
                           ("f" find-file "file")
                           ("F" find-file-other-window "other file")
                           ("v" (progn (split-window-right) (windmove-right)))
                           ("x" (progn (split-window-below) (windmove-down)))
                           ("o" delete-other-windows "delete-other")
                           ("a" switch-window)
                           ("s" helm-swap-window)
                           ("d" delete-window) ("D" delete-window) ("i" maximize-window) ("b" helm-buffers-list) ("q" nil)))

(key-chord-define-global "j."
                         (defhydra join-lines ()
                           ("<up>" join-line)
                           ("<down>" (join-line 1))
                           ("t" join-line)
                           ("n" (join-line 1))))

(key-chord-define-global "hh"
                             (defhydra my/key-chord-commands ()
                               ("k" kill-sexp)
                               ("b" helm-buffers-list :color blue)
                               ("f" find-file :color blue)
                               ("a" my/org-check-agenda :color blue)
                               ("." repeat)
                               ("i" imenu :color blue)
                               ("+" text-scale-increase)
                               ("q" nil)
                               ("-" text-scale-decrease)))

(key-chord-mode +1)

(provide 'init-keychord)
