;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		beginning-of-buffer
		c-electric-semi&comma
		save-some-buffers
		))

(setq mc/cmds-to-run-once
      '(
		c-electric-colon
		kill-region
		smart-tab
		toggle-input-method
		))
